name: CI Maven Project

on:
  workflow_dispatch:

jobs:
  CI-Non-Conterzation-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set Up Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Print Java and Maven version
        run: |
          java -version
          mvn -version

  CI-Non-Conterzation-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: CI-Non-Conterzation-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Run tests
        run: mvn test

  CI-Non-Conterzation-package:
    name: Package Application
    runs-on: ubuntu-latest
    needs: CI-Non-Conterzation-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Package with Maven
        run: mvn package

  CI-Non-Conterzation-verify:
    name: Verify the Package
    runs-on: ubuntu-latest
    needs: CI-Non-Conterzation-package

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Verify
        run: mvn verify
        
  CI-Non-Conterzation-Build-Artifact:
   name: Build Artifact
   runs-on: ubuntu-latest
   needs: CI-Non-Conterzation-verify

   steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.1
      with:
        java-version: '17'
        distribution: 'oracle'

    - name: Create staging directory and copy JAR
      run: mkdir staging &amp &amp cp target/*.jar staging

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Package
        path: staging

  CI-Non-Conterzation-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: CI-Non-Conterzation-package

    steps:
      - name: Deployment step
        run: echo "Deploying application..."

