name: CI Maven Project

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Project and Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set Up Java 17 (Oracle)
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: mvn clean install 
        # mvn clean install will clean, compile, and run tests.
        # It's more efficient to combine these steps in one Maven command.

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: target-directory
          path: target/ # Upload the entire target directory as an artifact


  package:
    name: Package Application
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully.
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set Up Java 17 (Oracle)
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4.6.2
        with:
          name: target-directory
          path: target/ # Download the target directory from the 'build' job.

      - name: Package with Maven
        run: mvn package -DskipTests 
        # Use -DskipTests since tests were already run in the 'build' job.

      - name: Create Staging Directory and Copy JAR
        run: |
          mkdir -p staging
          shopt -s nullglob
          files=(target/*.jar)
          if [ ${#files[@]} -gt 0 ]; then
            cp "${files[@]}" staging/
          else
            echo "No JAR files found in target/"
          fi

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Package
          path: staging

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Deployment Step
        run: echo "Deploying application..."
